version: '3.2'

services:
  client:
    build: .
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app/src
    ports:
      - 1234:1234
  api:
     depends_on:
      - database
     build: https://github.com/kontrollanten/med-crm-api.git
     restart: always
     environment:
       APP_ENV: development
       APP_FRONTEND_URL: http://localhost:1234
       CACHE_DRIVER: array
       DB_HOST: database
       DB_DATABASE: crm
       DB_USERNAME: root
       DB_PASSWORD: password
     ports:
       - 8000:8000
  database:
    image: mysql:5.7.21
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crm

